controllers/NodesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Nodes;
use app\models\NodesSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NodesController implements the CRUD actions for Nodes model.
 */
class NodesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),                
                'rules' => [
                    /*[
                        'actions' => ['login', 'signup'], // those action only which guest (?) user can access
                        'allow' => true,
                        'roles' => ['?'],                        
                    ],*/
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],  // those action only which authorized (@) user can access
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Nodes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NodesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Nodes model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Nodes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        // If no nodes exist in database and user tries to open the Dashboard, they are redirected here and shown a message
        $data = Yii::$app->request->get();
        isset($data['reason']) && $data['reason'] == 1 ? $message = "You should create a node first!" : $message = "";
       
        $model = new Nodes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'message' => $message,
            ]);
        }
    }

    /**
     * Updates an existing Nodes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        //$modelSensor = new NodeMeta();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
                //'modelSensor' => $modelSensor,
            ]);
        }
    }

    /**
     * Deletes an existing Nodes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Nodes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Nodes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Nodes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/ReadingsController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use yii\filters\AccessControl;
use app\models\Readings;
use app\models\ReadingsSearch;
use app\models\Settings;
use app\models\Sensors;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ReadingsController implements the CRUD actions for Readings model.
 */
class ReadingsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),                
                'rules' => [
                    [
                        'actions' => ['store'], // those action only which guest (?) user can access
                        'allow' => true,
                        'roles' => ['?'],                        
                    ],
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'store'],  // those action only which authorized (@) user can access
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
   
    /**
     * Lists all Readings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReadingsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort = ['defaultOrder' => ['timestamp' => 'DESC']]; // Show latest reading first

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Readings model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Readings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Readings();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Store a new sensor reading in the database.
     * Keep parameters short to save SRAM memory on Arduino
     * Add sensor_key=value in the URL
     * Example request URL: /garden-yii/web/index.php?r=readings%2Fstore&s=236E16&HpSA4d=23.54&MBvvWY=64.07
     * @see http://www.tutorialspoint.com/yii/yii_http_requests.htm Tutorial on Yii HTTP requests
     */
    public function actionStore()
    {
        // Store all POST/GET data in variable
        //$data = Yii::$app->request->post();
        $data = Yii::$app->request->get();

        // Load secret from settings table
        $setting = Settings::findOne(["setting_name" => 'secret']);

        // Check if the correct secret is set
        $secret = $setting->setting_value;
        if(!isset($data["s"]) || $data["s"] != $secret) {   // s is secret
            Yii::error("Secret is not set or incorrect");
            echo "Secret is not set or incorrect <br />";
            return;
        }

        // Walk through all the posted data
        foreach($data as $key => $value) {
            // Skip secret key and r parameters to only get the data points
            if($key != "s" && $key != "r") {
                // Check if the key exists and to which node it belongs
                if($sensor = Sensors::findOne(["sensor_key" => $key])){

                    $model = new Readings();

                    $model->node_id = $sensor['node_id'];
                    $model->sensor_key = $key;
                    $model->value = $value;

                    // Check the model for errors
                    if($model->validate())
                    {
                        echo 'No errors in the model!<br />';
                    }
                    else
                    {
                        echo "Errors found in the model!<br />";
                        $errors = $model->getErrors();
                        echo "<pre>";
                        print_r($errors);
                        echo "</pre>";
                        Yii::error($errors);
                    }

                    // Save the model in the database
                    if ($model->save()) {
                        echo "Saved!<br />";
                    }
                } else {
                    echo "No sensor with key ".$key." found!";
                    Yii::warning("No sensor with key ".$key." found!");         
                }
            }
        }

        return;
    }

    /**
     * Updates an existing Readings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Readings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Readings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Readings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Readings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SensorsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sensors;
use app\models\SensorsSearch;
use app\models\Nodes;
use app\models\Readings;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * SensorsController implements the CRUD actions for Sensors model.
 */
class SensorsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),                
                'rules' => [
                    /*[
                        'actions' => ['login', 'signup'], // those action only which guest (?) user can access
                        'allow' => true,
                        'roles' => ['?'],                        
                    ],*/
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],  // those action only which authorized (@) user can access
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Sensors models.
     * @return mixed
     */
    public function actionIndex()
    {
        // Find all nodes
        $nodes = Nodes::find();

        //$nodes = $query->orderBy('ID')
        //    ->all();

        // View sensors in table
        $searchModel = new SensorsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'nodes' => $nodes,
        ]);
    }

    /**
     * Displays a single Sensors model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sensors model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        // Find all nodes
        $query = Nodes::find();

        $nodes = $query->orderBy('ID')
                    ->all();

        // If at least one node exists, continue
        if(isset($nodes[0])) {
            $model = new Sensors();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->ID]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'nodes' => $nodes,
                ]);
            }
        } else {
            return $this->redirect(['nodes/create', 'reason' => 1]);
        }
    }

    /**
     * Updates an existing Sensors model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        // Find all nodes
        $query = Nodes::find();

        $nodes = $query->orderBy('ID')
                    ->all();
        
        $model = $this->findModel($id);

        // Store the current sensor key in a variable
        $old_sensor_key = $model->sensor_key;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // Store the new sensor key in a variable
            $new_sensor_key = $model->sensor_key;

            // On update of the sensor_key, update all readings with that sensor_key to the new sensor_key
            $command = Yii::$app->db->createCommand();
            $command->update('sensor_readings', array(
                'sensor_key' => $new_sensor_key,
            ), 'sensor_key=:sensor_key', array(':sensor_key' => $old_sensor_key));
            $command->execute();

            $model->save();
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'nodes' => $nodes,
            ]);
        }
    }

    /**
     * Deletes an existing Sensors model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sensors model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Sensors the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Sensors::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Generates a string of $length, then checks the database to see
     * if string is unique, and if not to generate a new string.
     * @param string $attribute In our case the sensor_key
     * @param int $length Length of the returned string
     * @return string Unique random string
     * @see http://www.jamesbarnsley.com/site/2016/04/25/generating-a-unique-random-string-for-model-properties-in-yii2/
     */
    public function uniqueString($attribute, $length = 32) {
            
        $randomString = Yii::$app->getSecurity()->generateRandomString($length);
                
        if(!Sensors::findOne([$attribute => $randomString])){
            return $randomString;
        } else {
            return $this->uniqueString($attribute, $length);
        }    
    }
}

views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use kartik\sidenav\SideNav;
use yii\helpers\Url;
use app\models\Settings;
use yii\bootstrap\Collapse;

AppAsset::register($this);

// Get site_title value from settings table in database
$site_title = Settings::findOne(['setting_name' => 'site_title']);

// Load layout.js for this view, after jQuery
$this->registerJsFile('@web/js/layout.js', ['depends' => '\yii\web\JqueryAsset']);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <div class="col-md-12" id="content">
        <!-- echo the main content of the page, the view -->
        <?= $content ?>
    </div>
</div>

<!--
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Arduino Garden <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
-->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use kartik\sidenav\SideNav;
use yii\helpers\Url;
use app\models\Settings;
use yii\bootstrap\Collapse;

AppAsset::register($this);

// Get site_title value from settings table in database
$site_title = Settings::findOne(['setting_name' => 'site_title']);

// Load layout.js for this view, after jQuery
$this->registerJsFile('@web/js/layout.js', ['depends' => '\yii\web\JqueryAsset']);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <div class="col-md-2 no-padding" id="sidebar">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $site_title->setting_value; ?></h3>
                <div id="toggle-menu">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                </div>
            </div>
        </div>

        <?php

        // Sidenav
        $item = 'home';
        echo SideNav::widget([
            'type' => 'default',
            'encodeLabels' => false,
            //'heading' => $site_title->setting_value,
            'containerOptions' => ['id' => 'sidenav'],
            'items' => [
                // Important: you need to specify url as 'controller/action',
                // not just as 'controller' even if default action is used.
                /*['label' => 'Dashboard', 'icon' => 'dashboard', 'url' => Url::to(['/dashboard/index', 'type'=>$type]), 'active' => ($item == 'dashboard')],
                ['label' => 'Books', 'icon' => 'book', 'items' => [
                    ['label' => '<span class="pull-right badge">10</span> New Arrivals', 'url' => Url::to(['/site/new-arrivals', 'type'=>$type]), 'active' => ($item == 'new-arrivals')],
                    ['label' => '<span class="pull-right badge">5</span> Most Popular', 'url' => Url::to(['/site/most-popular', 'type'=>$type]), 'active' => ($item == 'most-popular')],
                    ['label' => 'Read Online', 'icon' => 'cloud', 'items' => [
                        ['label' => 'Online 1', 'url' => Url::to(['/site/online-1', 'type'=>$type]), 'active' => ($item == 'online-1')],
                        ['label' => 'Online 2', 'url' => Url::to(['/site/online-2', 'type'=>$type]), 'active' => ($item == 'online-2')]
                    ]],
                ]],
                ['label' => '<span class="pull-right badge">3</span> Categories', 'icon' => 'tags', 'items' => [
                    ['label' => 'Fiction', 'url' => Url::to(['/site/fiction', 'type'=>$type]), 'active' => ($item == 'fiction')],
                    ['label' => 'Historical', 'url' => Url::to(['/site/historical', 'type'=>$type]), 'active' => ($item == 'historical')],
                    ['label' => '<span class="pull-right badge">2</span> Announcements', 'icon' => 'bullhorn', 'items' => [
                        ['label' => 'Event 1', 'url' => Url::to(['/site/event-1', 'type'=>$type]), 'active' => ($item == 'event-1')],
                        ['label' => 'Event 2', 'url' => Url::to(['/site/event-2', 'type'=>$type]), 'active' => ($item == 'event-2')]
                    ]],
                ]],*/
                ['label' => 'Dashboard', 'icon' => 'dashboard', 'url' => Url::to(['/dashboard/index']), 'active' => ($item == 'dashboard')],
                ['label' => 'Nodes', 'icon' => 'record', 'url' => Url::to(['/nodes/index']), 'active' => ($item == 'nodes')],
                ['label' => 'Sensors', 'icon' => 'cloud-upload', 'url' => Url::to(['/sensors/index']), 'active' => ($item == 'sensors')],
                ['label' => 'Readings', 'icon' => 'search', 'url' => Url::to(['/readings/index',]), 'active' => ($item == 'readings')],
                //['label' => 'Triggers', 'icon' => 'off', 'url' => Url::to(['/triggers/index']), 'active' => ($item == 'triggers')],
                ['label' => 'Settings', 'icon' => 'cog', 'url' => Url::to(['/settings/index']), 'active' => ($item == 'settings')],
                ['label' => 'Log out', 'icon' => 'user', 'url' => Url::to(['/site/logout']), 'active' => ($item == 'user'), 'options' => ['class' => 'border-top']],
            ],
        ]);     
        ?>

        <?php
        /*echo Collapse::widget([
            'encodeLabels' => false,
            'items' => [
                // equivalent to the above
                [
                    'label' => 'Click me!',
                    'content' => $sidenav.$sidenav_user,
                    // open its content by default
                    'contentOptions' => ['class' => 'in']
                ]
            ]
        ]);   */
        ?>

        
    </div>
    <div class="col-md-10" id="content">
        <!-- echo the main content of the page, the view -->
        <?= $content ?>
    </div>
</div>

<!--
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Arduino Garden <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
-->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>